const CoinActionTypes = {
  FETCH_COIN_REQUESTED: "FETCH_COIN_REQUESTED",
  FETCH_COIN_FAILED: "FETCH_COIN_FAILED",
  FETCH_COIN_SUCCEEDED: "FETCH_COIN_SUCCEEDED",
};

export default CoinActionTypes;
